/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// QuotaAutomationConfigApplyConfiguration represents a declarative configuration of the QuotaAutomationConfig type for use
// with apply.
//
// quotaAutomationConfig defines the configuration for the quota automation mechanism.
type QuotaAutomationConfigApplyConfiguration struct {
	// mode defines whether quota automation is enabled or disabled.
	Mode *kueuev1beta2.QuotaAutomationMode `json:"mode,omitempty"`
	// steps lists the steps to be taken for quota automation and defines in what order to take them.
	// Only present when mode is Automated.
	Steps []kueuev1beta2.QuotaAutomationStep `json:"steps,omitempty"`
	// configMap lists configuration parameters for the steps.
	// Only present when mode is Automated.
	ConfigMap map[kueuev1beta2.QuotaAutomationParameter]string `json:"configMap,omitempty"`
}

// QuotaAutomationConfigApplyConfiguration constructs a declarative configuration of the QuotaAutomationConfig type for use with
// apply.
func QuotaAutomationConfig() *QuotaAutomationConfigApplyConfiguration {
	return &QuotaAutomationConfigApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *QuotaAutomationConfigApplyConfiguration) WithMode(value kueuev1beta2.QuotaAutomationMode) *QuotaAutomationConfigApplyConfiguration {
	b.Mode = &value
	return b
}

// WithSteps adds the given value to the Steps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Steps field.
func (b *QuotaAutomationConfigApplyConfiguration) WithSteps(values ...kueuev1beta2.QuotaAutomationStep) *QuotaAutomationConfigApplyConfiguration {
	for i := range values {
		b.Steps = append(b.Steps, values[i])
	}
	return b
}

// WithConfigMap puts the entries into the ConfigMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ConfigMap field,
// overwriting an existing map entries in ConfigMap field with the same key.
func (b *QuotaAutomationConfigApplyConfiguration) WithConfigMap(entries map[kueuev1beta2.QuotaAutomationParameter]string) *QuotaAutomationConfigApplyConfiguration {
	if b.ConfigMap == nil && len(entries) > 0 {
		b.ConfigMap = make(map[kueuev1beta2.QuotaAutomationParameter]string, len(entries))
	}
	for k, v := range entries {
		b.ConfigMap[k] = v
	}
	return b
}
